### ISSUE TITLE
why not support matrix mul?

### ISSUE THREAD

**Issue by yubo1993** [intel/pailliercryptolib_python#37]
![image](https://user-images.githubusercontent.com/44748647/234787853-7fe799e5-85fd-4631-b96d-00df3547ad4f.png)

**Comment by fangxiaoran** [comment]
Hi @yubo1993, thanks for your interest. Could you provide more details, otherwise I can't give you an answer?

**Comment by fangxiaoran** [comment]
Close this issue since it has been inactive for more than 30 days.
